apiVersion: batch/v1
kind: Job
metadata:
  name: file-analysis-job
spec:
  template:
    spec:
      containers:
      - name: file-analyzer
        image: wizardml7/linux-malware-analysis:latest
        volumeMounts:
        - name: file-volume
          mountPath: /home/app/input
        env:
        - name: FILE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['file-name']
        - name: FILE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['file-id']
      restartPolicy: Never
      volumes:
      - name: file-volume
        persistentVolumeClaim:
          claimName: local-pvc
  backoffLimit: 4
